#ifndef ClunetCommands_h
#define ClunetCommands_h

#define CLUNET_COMMAND_DISCOVERY 0x00
#define CLUNET_COMMAND_DISCOVERY_RESPONSE 0x01
#define CLUNET_COMMAND_BOOT_CONTROL 0x02
#define CLUNET_COMMAND_REBOOT 0x03
#define CLUNET_COMMAND_BOOT_COMPLETED 0x04
#define CLUNET_COMMAND_TIME 0x08
#define CLUNET_COMMAND_TIME_INFO 0x09
#define CLUNET_COMMAND_PING 0xFE
#define CLUNET_COMMAND_PING_REPLY 0xFF
#define CLUNET_COMMAND_CHANNEL 0x10
#define CLUNET_COMMAND_CHANNEL_INFO 0x11
#define CLUNET_COMMAND_VOLUME 0x15
#define CLUNET_COMMAND_VOLUME_INFO 0x16
#define CLUNET_COMMAND_MUTE 0x17
#define CLUNET_COMMAND_EQUALIZER 0x18
#define CLUNET_COMMAND_EQUALIZER_INFO 0x19
#define CLUNET_COMMAND_FM 0x1C
#define CLUNET_COMMAND_FM_INFO 0x1D
#define CLUNET_COMMAND_POWER 0x1E
#define CLUNET_COMMAND_POWER_INFO 0x1F
#define CLUNET_COMMAND_SWITCH 0x20
#define CLUNET_COMMAND_SWITCH_INFO 0x21
#define CLUNET_COMMAND_BUTTON 0x22
#define CLUNET_COMMAND_BUTTON_INFO 0x23
#define CLUNET_COMMAND_TEMPERATURE 0x25
#define CLUNET_COMMAND_TEMPERATURE_INFO 0x26
#define CLUNET_COMMAND_HUMIDITY 0x27
#define CLUNET_COMMAND_HUMIDITY_INFO 0x28
#define CLUNET_COMMAND_PRESSURE 0x29
#define CLUNET_COMMAND_PRESSURE_INFO 0x2A
#define CLUNET_COMMAND_METEO 0x2E
#define CLUNET_COMMAND_METEO_INFO 0x2F
#define CLUNET_COMMAND_ONEWIRE_SEARCH 0x30
#define CLUNET_COMMAND_ONEWIRE_INFO 0x31
#define CLUNET_COMMAND_VOLTAGE 0x32
#define CLUNET_COMMAND_VOLTAGE_INFO 0x33
#define CLUNET_COMMAND_MOTION 0x40
#define CLUNET_COMMAND_MOTION_INFO 0x41
#define CLUNET_COMMAND_LIGHT_LEVEL 0x45
#define CLUNET_COMMAND_LIGHT_LEVEL_INFO 0x46
#define CLUNET_COMMAND_FAN 0x50
#define CLUNET_COMMAND_FAN_INFO 0x51
#define CLUNET_COMMAND_CHARGE 0x52
#define CLUNET_COMMAND_CHARGE_INFO 0x53
#define CLUNET_COMMAND_DOOR 0x55
#define CLUNET_COMMAND_DOOR_INFO 0x56
#define CLUNET_COMMAND_DIMMER 0x57
#define CLUNET_COMMAND_DIMMER_INFO 0x58
#define CLUNET_COMMAND_HEATFLOOR 0x60
#define CLUNET_COMMAND_HEATFLOOR_INFO 0x61
#define CLUNET_COMMAND_SERVO 0x66
#define CLUNET_COMMAND_SERVO_INFO 0x67
#define CLUNET_COMMAND_DEVICE_STATE 0x70
#define CLUNET_COMMAND_DEVICE_STATE_INFO 0x71
#define CLUNET_COMMAND_RC_BUTTON_PRESSED 0x75
#define CLUNET_COMMAND_RC_BUTTON_SEND 0x76
#define CLUNET_COMMAND_ANDROID 0xA0
#define CLUNET_COMMAND_DEBUG 0x99
#define CLUNET_COMMAND_SET_TIMER 0x09
#define CLUNET_COMMAND_BEEP 0x90

const char COMMAND_DISCOVERY[] PROGMEM = "DISCOVERY";
const char COMMAND_DISCOVERY_RESPONSE[] PROGMEM = "DISCOVERY_RESPONSE";
const char COMMAND_BOOT_CONTROL[] PROGMEM = "BOOT_CONTROL";
const char COMMAND_REBOOT[] PROGMEM = "REBOOT";
const char COMMAND_BOOT_COMPLETED[] PROGMEM = "BOOT_COMPLETED";
const char COMMAND_TIME[] PROGMEM = "TIME";
const char COMMAND_TIME_INFO[] PROGMEM = "TIME_INFO";
const char COMMAND_PING[] PROGMEM = "PING";
const char COMMAND_PING_REPLY[] PROGMEM = "PING_REPLY";
const char COMMAND_CHANNEL[] PROGMEM = "CHANNEL";
const char COMMAND_CHANNEL_INFO[] PROGMEM = "CHANNEL_INFO";
const char COMMAND_VOLUME[] PROGMEM = "VOLUME";
const char COMMAND_VOLUME_INFO[] PROGMEM = "VOLUME_INFO";
const char COMMAND_MUTE[] PROGMEM = "MUTE";
const char COMMAND_EQUALIZER[] PROGMEM = "EQUALIZER";
const char COMMAND_EQUALIZER_INFO[] PROGMEM = "EQUALIZER_INFO";
const char COMMAND_FM[] PROGMEM = "FM";
const char COMMAND_FM_INFO[] PROGMEM = "FM_INFO";
const char COMMAND_POWER[] PROGMEM = "POWER";
const char COMMAND_POWER_INFO[] PROGMEM = "POWER_INFO";
const char COMMAND_SWITCH[] PROGMEM = "SWITCH";
const char COMMAND_SWITCH_INFO[] PROGMEM = "SWITCH_INFO";
const char COMMAND_BUTTON[] PROGMEM = "BUTTON";
const char COMMAND_BUTTON_INFO[] PROGMEM = "BUTTON_INFO";
const char COMMAND_TEMPERATURE[] PROGMEM = "TEMPERATURE";
const char COMMAND_TEMPERATURE_INFO[] PROGMEM = "TEMPERATURE_INFO";
const char COMMAND_HUMIDITY[] PROGMEM = "HUMIDITY";
const char COMMAND_HUMIDITY_INFO[] PROGMEM = "HUMIDITY_INFO";
const char COMMAND_PRESSURE[] PROGMEM = "PRESSURE";
const char COMMAND_PRESSURE_INFO[] PROGMEM = "PRESSURE_INFO";
const char COMMAND_METEO[] PROGMEM = "METEO";
const char COMMAND_METEO_INFO[] PROGMEM = "METEO_INFO";
const char COMMAND_ONEWIRE_SEARCH[] PROGMEM = "ONEWIRE_SEARCH";
const char COMMAND_ONEWIRE_INFO[] PROGMEM = "ONEWIRE_INFO";
const char COMMAND_VOLTAGE[] PROGMEM = "VOLTAGE";
const char COMMAND_VOLTAGE_INFO[] PROGMEM = "VOLTAGE_INFO";
const char COMMAND_MOTION[] PROGMEM = "MOTION";
const char COMMAND_MOTION_INFO[] PROGMEM = "MOTION_INFO";
const char COMMAND_LIGHT_LEVEL[] PROGMEM = "LIGHT_LEVEL";
const char COMMAND_LIGHT_LEVEL_INFO[] PROGMEM = "LIGHT_LEVEL_INFO";
const char COMMAND_FAN[] PROGMEM = "FAN";
const char COMMAND_FAN_INFO[] PROGMEM = "FAN_INFO";
const char COMMAND_CHARGE[] PROGMEM = "CHARGE";
const char COMMAND_CHARGE_INFO[] PROGMEM = "CHARGE_INFO";
const char COMMAND_DOOR[] PROGMEM = "DOOR";
const char COMMAND_DOOR_INFO[] PROGMEM = "DOOR_INFO";
const char COMMAND_DIMMER[] PROGMEM = "DIMMER";
const char COMMAND_DIMMER_INFO[] PROGMEM = "DIMMER_INFO";
const char COMMAND_HEATFLOOR[] PROGMEM = "HEATFLOOR";
const char COMMAND_HEATFLOOR_INFO[] PROGMEM = "HEATFLOOR_INFO";
const char COMMAND_SERVO[] PROGMEM = "SERVO";
const char COMMAND_SERVO_INFO[] PROGMEM = "SERVO_INFO";
const char COMMAND_DEVICE_STATE[] PROGMEM = "DEVICE_STATE";
const char COMMAND_DEVICE_STATE_INFO[] PROGMEM = "DEVICE_STATE_INFO";
const char COMMAND_RC_BUTTON_PRESSED[] PROGMEM = "RC_BUTTON_PRESSED";
const char COMMAND_RC_BUTTON_SEND[] PROGMEM = "RC_BUTTON_SEND";
const char COMMAND_ANDROID[] PROGMEM = "ANDROID";
const char COMMAND_DEBUG[] PROGMEM = "DEBUG";
const char COMMAND_SET_TIMER[] PROGMEM = "SET_TIMER";
const char COMMAND_BEEP[] PROGMEM = "BEEP";

struct clunet_command {
  uint8_t code; 
  const char* name;
};

const struct clunet_command CLUNET_COMMANDS[] PROGMEM = 
{
	{CLUNET_COMMAND_DISCOVERY,          COMMAND_DISCOVERY},
	{CLUNET_COMMAND_DISCOVERY_RESPONSE, COMMAND_DISCOVERY_RESPONSE},
	{CLUNET_COMMAND_BOOT_CONTROL,		COMMAND_BOOT_CONTROL},
	{CLUNET_COMMAND_REBOOT,				COMMAND_REBOOT},
	{CLUNET_COMMAND_BOOT_COMPLETED,		COMMAND_BOOT_COMPLETED},
	{CLUNET_COMMAND_TIME,				COMMAND_TIME},
	{CLUNET_COMMAND_TIME_INFO,			COMMAND_TIME_INFO},
	{CLUNET_COMMAND_PING,				COMMAND_PING},
	{CLUNET_COMMAND_PING_REPLY,			COMMAND_PING_REPLY},
	{CLUNET_COMMAND_CHANNEL,			COMMAND_CHANNEL},
	{CLUNET_COMMAND_CHANNEL_INFO,		COMMAND_CHANNEL_INFO},
	{CLUNET_COMMAND_VOLUME,				COMMAND_VOLUME},
	{CLUNET_COMMAND_VOLUME_INFO,		COMMAND_VOLUME_INFO},
	{CLUNET_COMMAND_MUTE,				COMMAND_MUTE},
	{CLUNET_COMMAND_EQUALIZER,			COMMAND_EQUALIZER},
	{CLUNET_COMMAND_EQUALIZER_INFO,		COMMAND_EQUALIZER_INFO},
	{CLUNET_COMMAND_FM,					COMMAND_FM},
	{CLUNET_COMMAND_FM_INFO,			COMMAND_FM_INFO},
	{CLUNET_COMMAND_POWER,				COMMAND_POWER},
	{CLUNET_COMMAND_POWER_INFO,			COMMAND_POWER_INFO},
	{CLUNET_COMMAND_SWITCH,				COMMAND_SWITCH},
	{CLUNET_COMMAND_SWITCH_INFO,		COMMAND_SWITCH_INFO},
	{CLUNET_COMMAND_BUTTON,				COMMAND_BUTTON},
	{CLUNET_COMMAND_BUTTON_INFO,		COMMAND_BUTTON_INFO},
	{CLUNET_COMMAND_TEMPERATURE,		COMMAND_TEMPERATURE},
	{CLUNET_COMMAND_TEMPERATURE_INFO,	COMMAND_TEMPERATURE_INFO},
	{CLUNET_COMMAND_HUMIDITY,			COMMAND_HUMIDITY},
	{CLUNET_COMMAND_HUMIDITY_INFO,		COMMAND_HUMIDITY_INFO},
	{CLUNET_COMMAND_PRESSURE,			COMMAND_PRESSURE},
	{CLUNET_COMMAND_PRESSURE_INFO,		COMMAND_PRESSURE_INFO},
	{CLUNET_COMMAND_METEO,				COMMAND_METEO},
	{CLUNET_COMMAND_METEO_INFO,			COMMAND_METEO_INFO},
	{CLUNET_COMMAND_ONEWIRE_SEARCH,		COMMAND_ONEWIRE_SEARCH},
	{CLUNET_COMMAND_ONEWIRE_INFO,		COMMAND_ONEWIRE_INFO},
	{CLUNET_COMMAND_VOLTAGE,			COMMAND_VOLTAGE},
	{CLUNET_COMMAND_VOLTAGE_INFO,		COMMAND_VOLTAGE_INFO},
	{CLUNET_COMMAND_MOTION,				COMMAND_MOTION},
	{CLUNET_COMMAND_MOTION_INFO,		COMMAND_MOTION_INFO},
	{CLUNET_COMMAND_LIGHT_LEVEL,		COMMAND_LIGHT_LEVEL},
	{CLUNET_COMMAND_LIGHT_LEVEL_INFO,	COMMAND_LIGHT_LEVEL_INFO},
	{CLUNET_COMMAND_FAN,				COMMAND_FAN},
	{CLUNET_COMMAND_FAN_INFO,			COMMAND_FAN_INFO},
	{CLUNET_COMMAND_CHARGE,				COMMAND_CHARGE},
	{CLUNET_COMMAND_CHARGE_INFO,		COMMAND_CHARGE_INFO},
	{CLUNET_COMMAND_DOOR,				COMMAND_DOOR},
	{CLUNET_COMMAND_DOOR_INFO,			COMMAND_DOOR_INFO},
	{CLUNET_COMMAND_DIMMER,				COMMAND_DIMMER},
	{CLUNET_COMMAND_DIMMER_INFO,		COMMAND_DIMMER_INFO},
	{CLUNET_COMMAND_HEATFLOOR,			COMMAND_HEATFLOOR},
	{CLUNET_COMMAND_HEATFLOOR_INFO,		COMMAND_HEATFLOOR_INFO},
	{CLUNET_COMMAND_SERVO,				COMMAND_SERVO},
	{CLUNET_COMMAND_SERVO_INFO,			COMMAND_SERVO_INFO},
	{CLUNET_COMMAND_DEVICE_STATE,		COMMAND_DEVICE_STATE},
	{CLUNET_COMMAND_DEVICE_STATE_INFO,	COMMAND_DEVICE_STATE_INFO},
	{CLUNET_COMMAND_RC_BUTTON_PRESSED,	COMMAND_RC_BUTTON_PRESSED},
	{CLUNET_COMMAND_RC_BUTTON_SEND,		COMMAND_RC_BUTTON_SEND},
	{CLUNET_COMMAND_ANDROID,			COMMAND_ANDROID},
	{CLUNET_COMMAND_DEBUG,				COMMAND_DEBUG},
	{CLUNET_COMMAND_SET_TIMER,			COMMAND_SET_TIMER},
	{CLUNET_COMMAND_BEEP,				COMMAND_BEEP},
};

#endif
