#ifndef ClunetDevices_h
#define ClunetDevices_h

#define CLUNET_DEVICE_SUPRADIN 0x00
#define CLUNET_DEVICE_BROADCAST 0xFF

#define CLUNET_DEVICE_AUDIOBATH 0x0B
#define CLUNET_DEVICE_RELAY_1 0x14
#define CLUNET_DEVICE_RELAY_2 0x15
#define CLUNET_DEVICE_SOCKET_DIMMER 0x20
#define CLUNET_DEVICE_KITCHEN 0x1D
#define CLUNET_DEVICE_BATH_SENSORS 0x1E
#define CLUNET_DEVICE_WARDROBE 0x1F

#define CLUNET_DEVICE_SMARTHOME_BRIDGE 0x80
#define CLUNET_DEVICE_METEO 0x81
#define CLUNET_DEVICE_KITCHEN_LIGHT 0x82
#define CLUNET_DEVICE_WATER_SYSTEM 0x83
#define CLUNET_DEVICE_AUDIOBOX 0x84
#define CLUNET_DEVICE_SWING_SOCLE 0x85
#define CLUNET_DEVICE_ENERGY_METER 0x86

#define CLUNET_DEVICE_TELEPHONE 0x91


const char DEVICE_SUPRADIN[] PROGMEM = "SUPRADIN";
const char DEVICE_BROADCAST[] PROGMEM = "BROADCAST";
const char DEVICE_AUDIOBATH[] PROGMEM = "AUDIOBATH";
const char DEVICE_RELAY_1[] PROGMEM = "RELAY_1";
const char DEVICE_RELAY_2[] PROGMEM = "RELAY_2";
const char DEVICE_SOCKET_DIMMER[] PROGMEM = "SOCKET_DIMMER";
const char DEVICE_KITCHEN[] PROGMEM = "KITCHEN";
const char DEVICE_BATH_SENSORS[] PROGMEM = "BATH_SENSORS";
const char DEVICE_WARDROBE[] PROGMEM = "WARDROBE";
const char DEVICE_SMARTHOME_BRIDGE[] PROGMEM = "SMARTHOME_BRIDGE";
const char DEVICE_METEO[] PROGMEM = "METEO";
const char DEVICE_KITCHEN_LIGHT[] PROGMEM = "KITCHEN_LIGHT";
const char DEVICE_WATER_SYSTEM[] PROGMEM = "WATER_SYSTEM";
const char DEVICE_AUDIOBOX[] PROGMEM = "AUDIOBOX";
const char DEVICE_SWING_SOCLE[] PROGMEM = "SWING_SOCLE";
const char DEVICE_ENERGY_METER[] PROGMEM = "ENERGY_METER";
const char DEVICE_TELEPHONE[] PROGMEM = "TELEPHONE";


struct clunet_device {
  uint8_t code; 
  const char* name;
};

const struct clunet_device CLUNET_DEVICES[] PROGMEM = 
{
	{CLUNET_DEVICE_SUPRADIN,        DEVICE_SUPRADIN},
	{CLUNET_DEVICE_BROADCAST, 		DEVICE_BROADCAST},
	{CLUNET_DEVICE_AUDIOBATH,		DEVICE_AUDIOBATH},
	{CLUNET_DEVICE_RELAY_1,			DEVICE_RELAY_1},
	{CLUNET_DEVICE_RELAY_2,			DEVICE_RELAY_2},
	{CLUNET_DEVICE_SOCKET_DIMMER,	DEVICE_SOCKET_DIMMER},
	{CLUNET_DEVICE_KITCHEN,			DEVICE_KITCHEN},
	{CLUNET_DEVICE_BATH_SENSORS,	DEVICE_BATH_SENSORS},
	{CLUNET_DEVICE_WARDROBE,		DEVICE_WARDROBE},
	{CLUNET_DEVICE_SMARTHOME_BRIDGE,DEVICE_SMARTHOME_BRIDGE},
	{CLUNET_DEVICE_METEO,			DEVICE_METEO},
	{CLUNET_DEVICE_KITCHEN_LIGHT,	DEVICE_KITCHEN_LIGHT},
	{CLUNET_DEVICE_WATER_SYSTEM,	DEVICE_WATER_SYSTEM},
	{CLUNET_DEVICE_AUDIOBOX,		DEVICE_AUDIOBOX},
	{CLUNET_DEVICE_SWING_SOCLE,		DEVICE_SWING_SOCLE},
	{CLUNET_DEVICE_ENERGY_METER,	DEVICE_ENERGY_METER},
	{CLUNET_DEVICE_TELEPHONE,		DEVICE_TELEPHONE},
};

#endif
