#ifndef KitchenLight_h
#define KitchenLight_h

#define CLUNET_DEVICE_ID 0x82
#define CLUNET_DEVICE_NAME "KitchenLight"

#define TIMEZONE TZ_Europe_Samara

#define RELAY_0_ID 1
#define BUTTON_ID 3

#define BUTTON_PIN 12
#define LIGHT_PIN 14


#define PWM_RANGE 255
#define PWM_FREQUENCY 100

#define DELAY_BEFORE_TOGGLE 25
#define DELAY_BEFORE_PWM 500

#define PWM_DOWN_UP_CYCLE_TIME 4000
#define PWM_DOWN_UP_CYCLE_TIME_2 (int)(PWM_DOWN_UP_CYCLE_TIME/2)

#define HTTP_PORT 80

#define WIFI_CONNECT_TIMEOUT_MS 30000UL
#define WIFI_REBOOT_DELAY_MS 1500UL
#define WIFI_AP_PASSWORD "12345678"
#define WIFI_AP_SSID_PREFIX "KitchenLight"
#define WIFI_CONNECT_RETRY_INTERVAL_MS 5000UL
#define WIFI_SETTINGS_MAGIC 0x4B4C4954UL

#endif
